feat: support loading from envrc and env files

diff --git a/play-docker b/play-docker
--- a/play-docker
+++ b/play-docker
@@ -8,6 +8,7 @@ VERBOSE=0
 DRYRUN=false
 CONTAINERNAME=
 ARGFILE=
+ENVFILE=
 
 # Name of the file to search for by default.
 ARGFILENAME="PLAYDOCKER"
@@ -46,28 +47,30 @@ usage() {
   echo
   echo "Options:"
   echo "      --dry-run          Print out the resulting command."
+  echo "  -e                     Load environment variables from provided .env file."
+  echo "  -E                     Load environment variables from '.envrc'."
   echo "  -f, --file             Path to an $ARGFILENAME."
   echo "  -h, --help             Print usage"
   echo "  -i, --interactive      Run a basic shell in the docker container."
   echo "  -n, --name             The name of the container to be run."
   echo "                         Defaults to the working directory name."
   echo "  -v, --verbose          Raise the verbosity for each flag present."
-  exit 0
+  exit 1
 }
 
 err() {
-  /bin/echo -e "${ERRORFMT}${1}${RESETFMT}" 1>&2
+  printf "%b%s%b" "${ERRORFMT}" "${1}" "${RESETFMT}\n" 1>&2
 }
 
 warn() {
   if [ $VERBOSE -gt 0 ]; then
-    /bin/echo -e "${WARNFMT}${1}${RESETFMT}" 1>&2
+    printf "%b%s%b" "${WARNFMT}" "${1}" "${RESETFMT}\n" 1>&2
   fi
 }
 
 info() {
   if [ $VERBOSE -gt 1 ]; then
-    /bin/echo -e "${INFOFMT}${1}${RESETFMT}"
+    printf "%b%s%b" "${INFOFMT}" "${1}" "${RESETFMT}\n" 1>&2
   fi
 }
 
@@ -75,19 +78,19 @@ error_option() {
   err "$1: -$OPTARG"
   echo
   usage
-  exit 1
 }
 
 missing_argument() {
   err "Missing Required Argument: $1"
   echo
   usage
-  exit 1
 }
 
 parse_option() {
   case "$1" in
     dry-run) DRYRUN=true; VERBOSE=2 ;;
+    e) ENVFILE="${OPTARG}" ;;
+    E) ENVFILE=".envrc" ;;
     f|file) ARGFILE="${OPTARG}" ;;
     h|help) usage "verbose" ;;
     i|interactive) INTERACTIVE=true ;;
@@ -98,7 +101,7 @@ parse_option() {
   esac
 }
 
-while getopts ":f:hin:v-:" opt; do
+while getopts ":e:Ef:hin:v-:" opt; do
   # Normalize the long options.
   case "${opt}" in
     -)
@@ -137,18 +140,33 @@ fi
 # BEGIN PREPARATION
 RUNARGS="--name $CONTAINERNAME "
 
+if [ -f "${ENVFILE}" ]; then
+  while read -r line; do
+    # Ignore empty lines and lines that begin with a hash.
+    case "$line" in
+      ""|\#*) continue ;;
+    esac
+    # Format to ignore a leading `export `.
+    line="$(echo "${line}" | sed -E 's|^export\s+||')"
+    # Check to see that the line is vaguely in the shape of `KEY=VALUE`.
+    if echo "${line}" | grep -q -E '^[^=]+=.*$'; then
+      RUNARGS="${RUNARGS}-e ${line} "
+    fi
+  done < "$ENVFILE"
+fi
+
 while read -r line; do
   # Ignore empty lines and lines that begin with a hash.
   case "$line" in
     ""|\#*) continue ;;
   esac
   # Evaluate each part of the line to account for subshells and variables.
-  for part in $line; do
+  for part in ${line}; do
     case "$part" in
       ""|\#*) break ;;
     esac
 
-    parteval="$(eval "echo $part" 2>/dev/null)"
+    parteval="$(eval "printf '%s' $part" 2>/dev/null)"
     # shellcheck disable=SC2181
     if [ $? -eq 0 ]; then
       part="${parteval}"
